---
# Source: redis/templates/sentinel/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: exercise1-redis-node
  namespace: "default"
  labels:
    app.kubernetes.io/instance: exercise1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.4.2
    helm.sh/chart: redis-20.13.0
    app.kubernetes.io/component: node
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: exercise1
      app.kubernetes.io/name: redis
      app.kubernetes.io/component: node
